# Generated by Django 4.1.2 on 2022-11-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
    ]
