# Generated by Django 4.1.2 on 2022-11-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerlifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
