# Generated by Django 4.1.2 on 2022-12-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_powerlifting_delete_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerlifting',
            name='bench',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerlifting',
            name='deadlift',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerlifting',
            name='squat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
