# Generated by Django 4.1.2 on 2022-12-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_powerlifting_bench_powerlifting_deadlift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerlifting',
            name='bench_rank',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerlifting',
            name='deadlift_rank',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerlifting',
            name='squat_rank',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
